---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/location_npid_status/?location_id={location_id}":
    get:
      summary: Location NPID Status
      tags:
      - NPID Actions
      parameters:
      - name: location_id
        in: path
        description: location_id
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
  "/api/v1/merge":
    get:
      summary: list merges
      responses:
        '200':
          description: successful
    post:
      summary: create merge
      responses:
        '200':
          description: successful
  "/api/v1/merge/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show merge
      responses:
        '200':
          description: successful
    patch:
      summary: update merge
      responses:
        '200':
          description: successful
    put:
      summary: update merge
      responses:
        '200':
          description: successful
    delete:
      summary: delete merge
      responses:
        '200':
          description: successful
  "/v1/merge_people":
    post:
      summary: merge_people people_detail
      responses:
        '200':
          description: successful
      tags:
      - Deduplication
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                primary_person_doc_id:
                  type: string
                secondary_person_doc_id:
                  type: string
              required:
              - primary_person_doc_id
              - secondary_person_doc_id
  "/v1/rollback_merge":
    post:
      summary: rollback_merge merge
      tags:
      - Deduplication
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                primary_person_doc_id:
                  type: string
                secondary_person_doc_id:
                  type: string
              required:
              - primary_person_doc_id
              - secondary_person_doc_id
  "/api/v1/npid":
    get:
      summary: list npids
      responses:
        '200':
          description: successful
    post:
      summary: create npid
      responses:
        '200':
          description: successful
  "/api/v1/npid/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show npid
      responses:
        '200':
          description: successful
    patch:
      summary: update npid
      responses:
        '200':
          description: successful
    put:
      summary: update npid
      responses:
        '200':
          description: successful
    delete:
      summary: delete npid
      responses:
        '200':
          description: successful
  "/v1/assign_npids":
    post:
      summary: assign_npids npid
      tags:
      - NPID Actions
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                limit:
                  type: integer
                location_id:
                  type: integer
              required:
              - limit
              - location_id
  "/v1/add_person":
    post:
      summary: Create Person Details
      tags:
      - Person
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                given_name:
                  type: string
                family_name:
                  type: string
                gender:
                  type: string
                birthdate:
                  type: string
                  format: date
                birthdate_estimated:
                  type: boolean
                attributes:
                  type: object
                  properties:
                    current_district:
                      type: string
                    current_traditional_authority:
                      type: string
                    current_village:
                      type: string
                    home_district:
                      type: string
                    home_village:
                      type: string
                    home_traditional_authority:
                      type: string
                    occupation:
                      type: string
              required:
              - given_name
              - family_name
              - gender
              - birthdate
              - birthdate_estimated
              - attributes
              - home_district
              - home_village
              - home_traditional_authority
  "/v1/search_by_name_and_gender?given_name={given_name}&family_name={family_name}&gender={gender}":
    post:
      summary: search_by_name_and_gender people_detail
      tags:
      - Person
      parameters:
      - name: given_name
        in: path
        description: given_name
        required: true
        schema:
          type: string
      - name: family_name
        in: path
        description: family_name
        required: true
        schema:
          type: string
      - name: gender
        in: path
        description: gender
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
  "/v1/search_by_npid?npid={npid}":
    post:
      summary: search_by_npid people_detail
      tags:
      - Person
      parameters:
      - name: npid
        in: path
        description: npid
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
  "/v1/search_by_doc_id?doc_id={doc_id}":
    post:
      summary: search_by_doc_id people_detail
      tags:
      - Person
      parameters:
      - name: doc_id
        in: path
        description: doc_id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
  "/v1/update_person":
    post:
      summary: update_person people_detail
      tags:
      - Person
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                given_name:
                  type: string
                family_name:
                  type: string
                gender:
                  type: string
                birthdate:
                  type: string
                  format: date
                birthdate_estimated:
                  type: boolean
                attributes:
                  type: object
                  properties:
                    current_district:
                      type: string
                    current_traditional_authority:
                      type: string
                    current_village:
                      type: string
                    home_district:
                      type: string
                    home_village:
                      type: string
                    home_traditional_authority:
                      type: string
                    occupation:
                      type: string
                npid:
                  type: string
                doc_id:
                  type: string
              required:
              - doc_id
  "/v1/void_person/{doc_id}?void_reason={void_reason}":
    parameters:
    - name: doc_id
      in: path
      schema:
        doc_id:
          type: string
        void_reason:
          type: string
      required: true
    delete:
      summary: void people_detail
      tags:
      - Person
      responses:
        '200':
          description: successful
  "/v1/reassign_npid?doc_id={doc_id}":
    post:
      summary: reassign_npid people_detail
      tags:
      - Person
      parameters:
      - name: person
        in: path
        description: doc_id
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
  "/v1/search/people":
    post:
      summary: get people_match
      responses:
        '200':
          description: successful
  "/v1/person_changes_new":
    get:
      summary: pull_updates_new sync
      responses:
        '200':
          description: successful
  "/v1/person_changes_updates":
    get:
      summary: pull_updates sync
      responses:
        '200':
          description: successful
  "/v1/push_changes_new":
    post:
      summary: pushed_updates_new sync
      responses:
        '200':
          description: successful
  "/v1/push_changes_updates":
    post:
      summary: pushed_updates sync
      responses:
        '200':
          description: successful
  "/v1/push_footprints":
    post:
      summary: pushed_footprints sync
      responses:
        '200':
          description: successful
  "/v1/pull_npids":
    get:
      summary: pull_npids sync
      responses:
        '200':
          description: successful
  "/api/v1/user":
    get:
      summary: list users
      responses:
        '200':
          description: successful
    post:
      summary: create user
      responses:
        '200':
          description: successful
  "/api/v1/user/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      responses:
        '200':
          description: successful
    patch:
      summary: update user
      responses:
        '200':
          description: successful
    put:
      summary: update user
      responses:
        '200':
          description: successful
    delete:
      summary: delete user
      responses:
        '200':
          description: successful
  "/v1/register":
    post:
      summary: register user
      responses:
        '200':
          description: successful
  "/v1/login":
    post:
      summary: User Login
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
              - username
              - password
  "/v1/add_user":
    post:
      summary: add_user user
      tags:
      - User Management
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                location:
                  type: integer
              required:
              - username
              - password
              - location
  "/v1/verify_token/?token={token}":
    post:
      summary: verify_token user
      tags:
      - Authentication
      parameters:
      - name: token
        in: path
        description: token
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
  "/":
    get:
      summary: list users
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3004
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- bearerAuth: []
