---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/v1/add_person":
    post:
      summary: Creates person details
      tags:
      - People
      parameters: []
      responses:
        '201':
          description: person details created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                given_name:
                  type: string
                family_name:
                  type: string
                middle_name:
                  type: string
                birthdate:
                  type: date
                birthdate_estimated:
                  type: boolean
                gender:
                  type: boolean
                ancestry_district:
                  type: integer
                ancestry_ta:
                  type: integer
                ancestry_village:
                  type: integer
                home_district:
                  type: integer
                home_ta:
                  type: integer
                home_village:
                  type: integer
                npid:
                  type: string
                person_uuid:
                  type: binary
                date_registered:
                  type: datetime
                last_edited:
                  type: datetime
                location_created_at:
                  type: integer
                location_updated_at:
                  type: integer
              required:
              - first_name
              - last_name
              - gender
              - npid
              - person_uuid
              - date_registered
              - last_edited
              - location_created_at
              - location_updated_at
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
